### TEST REGISTER ✅
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "mmaruf",
  "firstName": "Muhammad Ma'ruf",
  "lastName": "",
  "password": "rahasia"
}

### TEST REGISTER ERROR ✅
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "",
  "firstName": "",
  "lastName": "",
  "password": ""
}

### TEST LOGIN ✅
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "mmaruf",
  "password": "masihrahasia"
}

### TEST GET PROFILE ✅
GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1ODgxMjQ1NCwiZXhwIjoxNzU4ODE2MDU0fQ.nlT--v2NubK_fE-qz7jVmzvft4Swuhpwaf0tNR2apyg

### TEST UPDATE PROFILE ✅
POST http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1NjM1NTk3MCwiZXhwIjoxNzU2MzU5NTcwfQ.0KPlH23gCWbwU7K5OaZoLj6HIzzBxSTAEgg2bvgNGGQ
Content-Type: application/json

{
  "firstName": "Muhammad",
  "lastName": "Ma'ruf"
}

### TEST UPDATE PASSWORD AJA ✅
POST http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1NjM1NTk3MCwiZXhwIjoxNzU2MzU5NTcwfQ.0KPlH23gCWbwU7K5OaZoLj6HIzzBxSTAEgg2bvgNGGQ
Content-Type: application/json

{
  "password": "masihrahasia"
}

### TEST CREATE DRAFT NEWS ✅
POST http://localhost:3000/api/news
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1ODgxNjE1OSwiZXhwIjoxNzU4ODE5NzU5fQ.foXjPtrgTSYfKtdLgJJMbed-xqvePm5_bDC_3WppDrw
Content-Type: multipart/form-data; boundary=boundary_string

--boundary_string
Content-Disposition: form-data; name="title"

Judul berita sebelas.
--boundary_string
Content-Disposition: form-data; name="subtitle"

Sub-judul berita sebelas.
--boundary_string
Content-Disposition: form-data; name="content"

Content berita sebelas.
--boundary_string
Content-Disposition: form-data; name="image"; filename="contoh.png"
Content-Type: image/png

< C:/Users/mmaruf23/Pictures/logo.png
--boundary_string--

### TEST GET NEWS SEBAGAI PUBLIC ✅
GET http://localhost:3000/api/news

### TEST GET NEWS SEBAGAI ADMIN ✅
GET http://localhost:3000/api/news?page=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1ODgxNDU4OCwiZXhwIjoxNzU4ODE4MTg4fQ.F9T-qFqS0jFj3-w5pYJHZP-1rAuohcB4cfAAMwbAioQ

### TEST GET NEWS BY ID ✅
GET http://localhost:3000/api/news/11

### TEST EDIT NEWS ✅
PUT http://localhost:3000/api/news
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1NjM2NzU2OCwiZXhwIjoxNzU2MzcxMTY4fQ.MZAQ2JOe-wZGtD9i0C3ETY8iZiOuyw4F2yaMyin3gMc
Content-Type: multipart/form-data; boundary=boundary_string

--boundary_string
Content-Disposition: form-data; name="id"

11
--boundary_string
# Content-Disposition: form-data; name="title"
# 
# Judul Berita Pertama Edited Kedua
# --boundary_string
# Content-Disposition: form-data; name="content"
# 
# Isi berita yang panjang edited
# --boundary_string
Content-Disposition: form-data; name="image"; filename="logo.png"
Content-Type: image/png

< C:/Users/mmaruf23/Pictures/logo.png
--boundary_string--

### TEST PUBLISH NEWS ✅
PATCH http://localhost:3000/api/news/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1NjM2NzU2OCwiZXhwIjoxNzU2MzcxMTY4fQ.MZAQ2JOe-wZGtD9i0C3ETY8iZiOuyw4F2yaMyin3gMc


### TEST DELETE NEWS ✅
DELETE http://localhost:3000/api/news/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Im1tYXJ1ZiIsImlhdCI6MTc1NjM2NzU2OCwiZXhwIjoxNzU2MzcxMTY4fQ.MZAQ2JOe-wZGtD9i0C3ETY8iZiOuyw4F2yaMyin3gMc

### TEST GET IMAGE ✅
GET http://localhost:3000/file/images/1758804608669.png